language: php

php:
  - 7.3

addons:
  chrome: stable

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate --seed -vvv
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpunit

after_success:
  - chmod +x ./post_test_deploy.sh; ./post_test_deploy.sh